// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbwepxwwnauhvptxqqic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRid2VweHd3bmF1aHZwdHhxcWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1ODA3NzgsImV4cCI6MjA3NzE1Njc3OH0.Tzb40kYVD9Kj1fv7XNtihFjlVLPyqUGBUDTHSLcYrNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});